language: csharp
solution: SupplyChainManagement.sln
env: MONO_LOG_LEVEL=debug MONO_LOG_MASK=dll
install:
  - sudo apt-get install sqlite3 
  - nuget restore SupplyChainManagement.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release SupplyChainManagement.sln
