language: csharp
solution: SupplyChainManagement.sln
install:
  - sudo apt-get install libsqlite3
  - nuget restore SupplyChainManagement.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release SupplyChainManagement.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./SupplyChainManagementTest/bin/Release/SupplyChainManagementTest.dll
